---
# tasks file for docker-registry
# tasks file for docker
# tasks file for docker
- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: anisellouz/devops
    tag: devops anisellouz/devops
    push: yes
