---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: anisell
    password: fadhel76220819
    
#- name: Tag and push to docker hub
#  docker_image:
#    name: devops
#    repository: anisellouz/livraison
#    tag: 7.0
#    push: yes
#    source: local
    
- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: anisell/livraison
    tag: end
    push: yes
