---
# tasks file for docker-registry
- name: Log into DockerHub
  docker_login:
    username: anisellouz
    password: 280be307-c824-44d9-8bbf-e1d540c02fd5
    
#- name: Tag and push to docker hub
#  docker_image:
#    name: devops
#    repository: anisellouz/livraison
#    tag: 7.0
#    push: yes
#    source: local
    
- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: anisellouz/livraison
    tag: end
    push: yes
