---
# tasks file for docker-registry
# tasks file for docker
# tasks file for docker
- name: pull an image
  docker_image:
    name: anisellouz/devops
    source: pull
- name: Tag and push to docker hub
  docker_image:
    name: anisellouz/devops:latest
    repository: anisellouz/livraison:latest
    push: yes
    source: local
